version: '3'

services:
  database:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432

  # jaeger ??
